wchaws/serverless-image-handler

source/ecs-image-handler/src/processor/index.ts, source/ecs-image-handler/src/store.ts
=> chore: add inline doc

source/ecs-image-handler/src/default.ts, source/ecs-image-handler/src/index.ts, source/ecs-image-handler/src/processor/image/index.ts, source/ecs-image-handler/test/default.test.ts, source/ecs-image-handler/test/processor/index.test.ts
=> feat: add custom style delimiter '@!'

source/ecs-image-handler/.eslintrc.json, source/ecs-image-handler/src/processor/image/index.ts
=> eslint: enforce format

source/ecs-image-handler/.eslintrc.json, source/ecs-image-handler/src/debug.ts
=> chore: enforce eslint

source/ecs-image-handler/src/processor/image/auto-orient.ts, source/ecs-image-handler/src/processor/image/blur.ts, source/ecs-image-handler/src/processor/image/bright.ts, source/ecs-image-handler/src/processor/image/contrast.ts, source/ecs-image-handler/src/processor/image/crop.ts, source/ecs-image-handler/src/processor/image/format.ts, source/ecs-image-handler/src/processor/image/grey.ts, source/ecs-image-handler/src/processor/image/index.ts, source/ecs-image-handler/src/processor/image/indexcrop.ts, source/ecs-image-handler/src/processor/image/interlace.ts, source/ecs-image-handler/src/processor/image/rotate.ts, source/ecs-image-handler/src/processor/image/sharpen.ts, source/ecs-image-handler/test/processor/image/auto-orient.test.ts, source/ecs-image-handler/test/processor/image/blur.test.ts, source/ecs-image-handler/test/processor/image/bright.test.ts, source/ecs-image-handler/test/processor/image/contrast.test.ts, source/ecs-image-handler/test/processor/image/crop.test.ts, source/ecs-image-handler/test/processor/image/format.test.ts, source/ecs-image-handler/test/processor/image/grey.test.ts, source/ecs-image-handler/test/processor/image/indexcrop.test.ts, source/ecs-image-handler/test/processor/image/interlace.test.ts, source/ecs-image-handler/test/processor/image/rotate.test.ts, source/ecs-image-handler/test/processor/image/sharpen.test.ts
Close: #14 
Close: #15 
Close: #16 
Close: #17 
Close: #18 
Close: #19 
**Checklist**
=> Add Function [blur bright contrast crop grey format rotate sharpen]

source/ecs-image-handler/src/processor/image/rotate.ts, source/ecs-image-handler/src/processor/image/sharpen.ts
Close: #24
Close: #25 
**Checklist**
=> Fix bug 24,25

source/constructs/README.md, source/constructs/lib/ecs-image-handler.ts
=> feat: support use existing s3 bucket

source/constructs/README.md, source/ecs-image-handler/Dockerfile, source/ecs-image-handler/package.json
=> chore: set minimal node version to 12

source/constructs/README.md
=> docs: update

.github/workflows/upgrade-dependencies.yml, source/constructs/package.json, source/ecs-image-handler/package.json
=> fix: upgrade-deps

source/constructs/README.md, source/constructs/bin/constructs.ts, source/ecs-image-handler/test/store.test.ts
=> chore: add trouble shooting in README and support change stack name

.github/workflows/build.yml, source/constructs/package.json
=> fix: build error on node 12

source/constructs/bin/constructs.ts
=> chore: add tags

source/constructs/lib/constructs-stack.ts, source/constructs/lib/lambda-image-handler.ts
=> feat: manual add OriginAccessIdentity policy for s3

.github/workflows/build.yml, source/constructs/lib/constructs-stack.ts, source/constructs/lib/lambda-image-handler.ts, source/new-image-handler/src/processor/image/crop.ts, source/new-image-handler/src/processor/image/indexcrop.ts
=> feat: add AltDomainParam

source/constructs/lib/constructs-stack.ts, source/constructs/lib/lambda-image-handler.ts
=> feat: add IamCert param support

source/new-image-handler/src/processor/image/bright.ts, source/new-image-handler/src/processor/image/contrast.ts
Fix: #26
Fix: #27 
**Checklist**
=> fix: incorrect brightness #26

source/new-image-handler/src/processor/image/bright.ts
=> fix: fine tune bright

source/new-image-handler/src/index-lambda.ts, source/new-image-handler/src/index.ts
=> feat: enable animated be default

source/new-image-handler/src/processor/image/resize.ts, source/new-image-handler/test/processor/image/resize.test.ts
=> fix: resize,l_100

source/new-image-handler/Dockerfile
=> chore: add font in Dockerfile

source/new-image-handler/src/imagemagick.ts, source/new-image-handler/test/imagemagick.test.ts
=> chore: add src/imagemagick.ts

source/new-image-handler/package.json, source/new-image-handler/test/bench/perf.ts, source/new-image-handler/yarn.lock
=> chore: add benchmark of sharp vs imagemgick

source/new-image-handler/Dockerfile, source/new-image-handler/src/imagemagick.ts, source/new-image-handler/src/processor/image/quality.ts, source/new-image-handler/test/imagemagick.test.ts, source/new-image-handler/test/processor/image/quality.test.ts
=> fix: support relative quality

source/new-image-handler/Dockerfile.lambda.deps, source/new-image-handler/ImageMagick.Makefile, source/new-image-handler/src/imagemagick.ts
=> fix: relative quality is not supported in lambda env #71

source/new-image-handler/src/imagemagick.ts, source/new-image-handler/src/processor/image/format.ts, source/new-image-handler/test/processor/index.test.ts
=> fix: format,jpg forgif will show all frames

source/new-image-handler/Dockerfile.lambda.deps
=> fix: Rpmdb checksum is invalid: dCDPT(pkg checksums)

source/constructs/lib/lambda-image-handler.ts
=> refactor: shorter cloudfront policy name

source/new-image-handler/Dockerfile.dev, source/new-image-handler/src/processor/image/resize.ts
=> feat: support gif resize for container mode

source/new-image-handler/src/processor/image/rotate.ts, source/new-image-handler/test/processor/index.test.ts
=> fix: incorrect size when rotate after resize

source/new-image-handler/Dockerfile
support the order of text and image in mixed watermark
support the align of text and image in mixed watermark
support the interval of text and image in mixed watermark
plus:
support x, y position and vertical offset for image watermark
=> support the mixed  image and text watermark feature

source/new-image-handler/src/processor/image/watermark.ts
feature:
1. x,y pot for pure text and mixed watermark
bug fix:
1. when the interval param is too big, it will cause the api failed
2. support the png image opacity setting
=> feature: support x,y opt for pure text and mixed watermarks

source/new-image-handler/Dockerfile, source/new-image-handler/Dockerfile.dev, source/new-image-handler/Dockerfile.lambda.deps, source/new-image-handler/package.json, source/new-image-handler/src/processor/image/jpeg.js, source/new-image-handler/src/processor/image/quality.ts, source/new-image-handler/test/processor/image/quality.test.ts, source/new-image-handler/test/processor/image/rounded-corners.test.ts, source/new-image-handler/tsconfig.eslint.json, source/new-image-handler/tsconfig.jest.json, source/new-image-handler/tsconfig.json
=> chore!: get rid of imagemagick #86

source/new-image-handler/yarn.lock
=> chore: upgrade sharp to v0.30.1

source/new-image-handler/src/index-lambda.ts, source/new-image-handler/src/index.ts, source/new-image-handler/src/processor/image/format.ts, source/new-image-handler/src/processor/image/index.ts, source/new-image-handler/src/processor/image/info.ts, source/new-image-handler/src/processor/index.ts, source/new-image-handler/test/processor/image/auto-orient.test.ts, source/new-image-handler/test/processor/image/blur.test.ts, source/new-image-handler/test/processor/image/bright.test.ts, source/new-image-handler/test/processor/image/circle.test.ts, source/new-image-handler/test/processor/image/contrast.test.ts, source/new-image-handler/test/processor/image/crop.test.ts, source/new-image-handler/test/processor/image/format.test.ts, source/new-image-handler/test/processor/image/grey.test.ts, source/new-image-handler/test/processor/image/indexcrop.test.ts, source/new-image-handler/test/processor/image/info.test.ts, source/new-image-handler/test/processor/image/interlace.test.ts, source/new-image-handler/test/processor/image/quality.test.ts, source/new-image-handler/test/processor/image/resize.test.ts, source/new-image-handler/test/processor/image/rotate.test.ts, source/new-image-handler/test/processor/image/rounded-corners.test.ts, source/new-image-handler/test/processor/image/sharpen.test.ts, source/new-image-handler/test/processor/image/utils.ts, source/new-image-handler/test/processor/image/watermark.test.ts, source/new-image-handler/test/processor/index.test.ts
=> feat: support info action

source/constructs/cdk.context.json, source/constructs/lib/ecs-image-handler.ts, source/constructs/test/__snapshots__/ecs-image-handler.test.ts.snap, source/constructs/test/ecs-image-handler.test.ts
=> feat: support multiple s3 image bucket for ecs-image-handler

source/new-image-handler/src/index.ts, source/new-image-handler/yarn.lock
=> refactor: ecs-image-handler post api

source/new-image-handler/src/processor/image/format.ts, source/new-image-handler/test/processor/image/format.test.ts
=> fix: format not support gif,jpeg

source/new-image-handler/src/processor/image/watermark.ts
On behalf of JiaTing. She completed the font feature ( _type_ parameter for watermark action)
**Checklist**
=> Type feature

source/new-image-handler/package.json, source/new-image-handler/src/index.ts, source/new-image-handler/src/processor/image/index.ts, source/new-image-handler/src/processor/image/watermark.ts, source/new-image-handler/test/processor/image/info.test.ts, source/new-image-handler/test/processor/image/quality.test.ts, source/new-image-handler/test/processor/image/utils.ts
=> feat: warkermark shadow workaround

source/constructs/lib/constructs-stack.ts
=> chore: add solution id for ecs-image-handler

source/constructs/lib/lambda-image-handler.ts
=> fix: reserved keys used in this request: AWS_REGION

source/constructs/lib/ecs-image-handler.ts
=> fix: missing x-bucket for cloudfront distribution

source/new-image-handler/src/index.ts, source/new-image-handler/src/processor/image/index.ts, source/new-image-handler/src/processor/index.ts, source/new-image-handler/src/processor/style.ts, source/new-image-handler/src/store.ts, source/new-image-handler/test/processor/image/utils.ts
ETag and last-modified.
UT Passed.
**Checklist**
=> Client cache

source/new-image-handler/src/index.ts, source/new-image-handler/src/processor/image/watermark.ts
Watermark process with _fill_ parameter is not _g_ is given.
fix: the bug of watermark parameters.
**Checklist**
=> Fill fix g

source/constructs/bin/constructs.ts, source/constructs/cdk.context.json
Allow the tags be written to cdk.context.json.
I have to test the existence of the tags in config or the loop will fail in case of no tags is provided.
**Checklist**
=> put customer tags in config

source/new-image-handler/src/index.ts
Protect server from taking too many requests.
**Checklist**
=> feat: throtlling feature added.

source/new-image-handler/src/processor/image/format.ts, source/new-image-handler/src/processor/image/resize.ts, source/new-image-handler/test/index-lambda.test.ts
https://github.com/lovell/sharp/issues/3176
**Checklist**
=> fix: gif resize slow

source/new-image-handler/package.json, source/new-image-handler/src/index.ts, source/new-image-handler/src/processor/image/index.ts, source/new-image-handler/test/index-lambda.test.ts, source/new-image-handler/test/processor/index.test.ts, source/new-image-handler/yarn.lock
=> fix: post api content-type is not a valid mime type

source/new-image-handler/package.json, source/new-image-handler/src/index-lambda.ts, source/new-image-handler/src/index.ts, source/new-image-handler/src/processor/image/index.ts, source/new-image-handler/src/store.ts, source/new-image-handler/test/index-lambda.test.ts, source/new-image-handler/test/processor/index.test.ts, source/new-image-handler/yarn.lock
=> chore: disable mime.lookup

source/constructs/lib/ecs-image-handler.ts, source/constructs/test/__snapshots__/ecs-image-handler.test.ts.snap
=> fix: enableECSManagedTags

source/constructs/lib/lambda-image-handler.ts
=> fix: upgrade node v12 to v14

source/new-image-handler/src/processor/image/index.ts, source/new-image-handler/src/processor/image/strip-metadata.ts, source/new-image-handler/test/processor/index.test.ts
=> feat: add strip-metadata action api

source/new-image-handler/src/processor/image/watermark.ts
=> fix bug:correct image width&height when image orientation bigger than 5

source/new-image-handler/src/processor/image/watermark.ts
1. remove svg text watermark
2. improve feature about auto resize  bigger watermark
3. fix bug: watermark was broken
=> refactoring and fix bug  using sharp 0.31.0 version's new features

source/new-image-handler/src/processor/image/watermark.ts
fix issue:
use shadow param as the shadow opacity value
=> use shadow as the opacity value

source/new-image-handler/test/e2e/README.md, source/new-image-handler/test/e2e/mkhtml.py
=> chore: add mkhtml

source/new-image-handler/src/processor/image/watermark.ts
support crop if the  watermark exceed the background image
=> support crop if the  watermark exceed the background image

source/constructs/README.md, source/new-image-handler/test/bench/README.md, source/new-image-handler/test/bench/curl.sh, source/new-image-handler/test/bench/urls.txt, source/new-image-handler/test/e2e/README.md
=> docs: update readme

source/new-image-handler/src/processor/image/_base.ts, source/new-image-handler/src/processor/image/watermark.ts, source/new-image-handler/test/processor/image/_base.test.ts
=> fix: add split1 function to support base64url

source/new-image-handler/yarn.lock
=> chore: upgrade sharp to 0.31.2 to fix up stream regressions bugs

source/new-image-handler/package.json, source/new-image-handler/src/processor/image/watermark.ts, source/new-image-handler/yarn.lock
fix issues:
1. base64 to base64url
2. html encode
=> fix text decode issue

source/constructs/cdk.context.json, source/constructs/lib/ecs-image-handler.ts, source/constructs/package.json, source/constructs/test/ecs-image-handler.test.ts, source/new-image-handler/src/config.ts, source/new-image-handler/src/default.ts, source/new-image-handler/src/index.ts, source/new-image-handler/src/processor/image/index.ts
=> feat: support parameter store to bypass large gif processing

source/new-image-handler/src/processor/image/index.ts, source/new-image-handler/src/processor/image/threshold.ts, source/new-image-handler/test/fixtures/.gitignore, source/new-image-handler/test/processor/image/threshold.test.ts, source/new-image-handler/test/processor/index.test.ts
=> feat: add threshold

source/new-image-handler/.dockerignore, source/new-image-handler/src/index.ts, source/new-image-handler/src/store.ts, source/new-image-handler/test/index-lambda.test.ts, source/new-image-handler/test/processor/index.test.ts
=> fix: missing bucket name for cache key
